// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinanceApp.Infrastructure.Persistence;

#nullable disable

namespace PersonalFinanceApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911200048_Adding Seed Data")]
    partial class AddingSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanDeleteDirectly")
                        .HasColumnType("bit");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("NormalBalance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanDeleteDirectly = true,
                            Category = 1,
                            NormalBalance = 1
                        },
                        new
                        {
                            Id = 2,
                            CanDeleteDirectly = true,
                            Category = 2,
                            NormalBalance = 2
                        },
                        new
                        {
                            Id = 3,
                            CanDeleteDirectly = false,
                            Category = 3,
                            NormalBalance = 3
                        },
                        new
                        {
                            Id = 4,
                            CanDeleteDirectly = false,
                            Category = 4,
                            NormalBalance = 3
                        },
                        new
                        {
                            Id = 5,
                            CanDeleteDirectly = false,
                            Category = 5,
                            NormalBalance = 1
                        },
                        new
                        {
                            Id = 6,
                            CanDeleteDirectly = false,
                            Category = 7,
                            NormalBalance = 3
                        },
                        new
                        {
                            Id = 7,
                            CanDeleteDirectly = false,
                            Category = 6,
                            NormalBalance = 3
                        });
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("AccountTypeId", "LanguageId")
                        .IsUnique();

                    b.ToTable("AccountTypeTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            LanguageId = 1,
                            Translation = "Expense"
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeId = 1,
                            LanguageId = 2,
                            Translation = "هزینه"
                        },
                        new
                        {
                            Id = 3,
                            AccountTypeId = 1,
                            LanguageId = 3,
                            Translation = "Gider"
                        },
                        new
                        {
                            Id = 4,
                            AccountTypeId = 1,
                            LanguageId = 4,
                            Translation = "Dépense"
                        },
                        new
                        {
                            Id = 5,
                            AccountTypeId = 1,
                            LanguageId = 5,
                            Translation = "Aufwand"
                        },
                        new
                        {
                            Id = 6,
                            AccountTypeId = 1,
                            LanguageId = 6,
                            Translation = "مصروف"
                        },
                        new
                        {
                            Id = 7,
                            AccountTypeId = 1,
                            LanguageId = 7,
                            Translation = "Gasto"
                        },
                        new
                        {
                            Id = 8,
                            AccountTypeId = 1,
                            LanguageId = 8,
                            Translation = "Spesa"
                        },
                        new
                        {
                            Id = 9,
                            AccountTypeId = 1,
                            LanguageId = 9,
                            Translation = "Расход"
                        },
                        new
                        {
                            Id = 10,
                            AccountTypeId = 1,
                            LanguageId = 10,
                            Translation = "费用"
                        },
                        new
                        {
                            Id = 11,
                            AccountTypeId = 1,
                            LanguageId = 11,
                            Translation = "費用"
                        },
                        new
                        {
                            Id = 12,
                            AccountTypeId = 1,
                            LanguageId = 12,
                            Translation = "Kostnad"
                        },
                        new
                        {
                            Id = 13,
                            AccountTypeId = 2,
                            LanguageId = 1,
                            Translation = "Income"
                        },
                        new
                        {
                            Id = 14,
                            AccountTypeId = 2,
                            LanguageId = 2,
                            Translation = "درآمد"
                        },
                        new
                        {
                            Id = 15,
                            AccountTypeId = 2,
                            LanguageId = 3,
                            Translation = "Gelir"
                        },
                        new
                        {
                            Id = 16,
                            AccountTypeId = 2,
                            LanguageId = 4,
                            Translation = "Revenu"
                        },
                        new
                        {
                            Id = 17,
                            AccountTypeId = 2,
                            LanguageId = 5,
                            Translation = "Ertrag"
                        },
                        new
                        {
                            Id = 18,
                            AccountTypeId = 2,
                            LanguageId = 6,
                            Translation = "إيراد"
                        },
                        new
                        {
                            Id = 19,
                            AccountTypeId = 2,
                            LanguageId = 7,
                            Translation = "Ingreso"
                        },
                        new
                        {
                            Id = 20,
                            AccountTypeId = 2,
                            LanguageId = 8,
                            Translation = "Entrata"
                        },
                        new
                        {
                            Id = 21,
                            AccountTypeId = 2,
                            LanguageId = 9,
                            Translation = "Доход"
                        },
                        new
                        {
                            Id = 22,
                            AccountTypeId = 2,
                            LanguageId = 10,
                            Translation = "收入"
                        },
                        new
                        {
                            Id = 23,
                            AccountTypeId = 2,
                            LanguageId = 11,
                            Translation = "収益"
                        },
                        new
                        {
                            Id = 24,
                            AccountTypeId = 2,
                            LanguageId = 12,
                            Translation = "Intäkt"
                        },
                        new
                        {
                            Id = 25,
                            AccountTypeId = 3,
                            LanguageId = 1,
                            Translation = "Person"
                        },
                        new
                        {
                            Id = 26,
                            AccountTypeId = 3,
                            LanguageId = 2,
                            Translation = "شخص"
                        },
                        new
                        {
                            Id = 27,
                            AccountTypeId = 3,
                            LanguageId = 3,
                            Translation = "Kişi"
                        },
                        new
                        {
                            Id = 28,
                            AccountTypeId = 3,
                            LanguageId = 4,
                            Translation = "Personne"
                        },
                        new
                        {
                            Id = 29,
                            AccountTypeId = 3,
                            LanguageId = 5,
                            Translation = "Person"
                        },
                        new
                        {
                            Id = 30,
                            AccountTypeId = 3,
                            LanguageId = 6,
                            Translation = "شخص"
                        },
                        new
                        {
                            Id = 31,
                            AccountTypeId = 3,
                            LanguageId = 7,
                            Translation = "Persona"
                        },
                        new
                        {
                            Id = 32,
                            AccountTypeId = 3,
                            LanguageId = 8,
                            Translation = "Persona"
                        },
                        new
                        {
                            Id = 33,
                            AccountTypeId = 3,
                            LanguageId = 9,
                            Translation = "Контрагент"
                        },
                        new
                        {
                            Id = 34,
                            AccountTypeId = 3,
                            LanguageId = 10,
                            Translation = "个人"
                        },
                        new
                        {
                            Id = 35,
                            AccountTypeId = 3,
                            LanguageId = 11,
                            Translation = "個人"
                        },
                        new
                        {
                            Id = 36,
                            AccountTypeId = 3,
                            LanguageId = 12,
                            Translation = "Person"
                        },
                        new
                        {
                            Id = 37,
                            AccountTypeId = 4,
                            LanguageId = 1,
                            Translation = "Bank Account"
                        },
                        new
                        {
                            Id = 38,
                            AccountTypeId = 4,
                            LanguageId = 2,
                            Translation = "حساب بانکی"
                        },
                        new
                        {
                            Id = 39,
                            AccountTypeId = 4,
                            LanguageId = 3,
                            Translation = "Banka Hesabı"
                        },
                        new
                        {
                            Id = 40,
                            AccountTypeId = 4,
                            LanguageId = 4,
                            Translation = "Compte bancaire"
                        },
                        new
                        {
                            Id = 41,
                            AccountTypeId = 4,
                            LanguageId = 5,
                            Translation = "Bankkonto"
                        },
                        new
                        {
                            Id = 42,
                            AccountTypeId = 4,
                            LanguageId = 6,
                            Translation = "حساب مصرفي"
                        },
                        new
                        {
                            Id = 43,
                            AccountTypeId = 4,
                            LanguageId = 7,
                            Translation = "Cuenta bancaria"
                        },
                        new
                        {
                            Id = 44,
                            AccountTypeId = 4,
                            LanguageId = 8,
                            Translation = "Conto bancario"
                        },
                        new
                        {
                            Id = 45,
                            AccountTypeId = 4,
                            LanguageId = 9,
                            Translation = "Банковский счет"
                        },
                        new
                        {
                            Id = 46,
                            AccountTypeId = 4,
                            LanguageId = 10,
                            Translation = "银行账户"
                        },
                        new
                        {
                            Id = 47,
                            AccountTypeId = 4,
                            LanguageId = 11,
                            Translation = "銀行口座"
                        },
                        new
                        {
                            Id = 48,
                            AccountTypeId = 4,
                            LanguageId = 12,
                            Translation = "Bankkonto"
                        },
                        new
                        {
                            Id = 49,
                            AccountTypeId = 5,
                            LanguageId = 1,
                            Translation = "Cash"
                        },
                        new
                        {
                            Id = 50,
                            AccountTypeId = 5,
                            LanguageId = 2,
                            Translation = "حساب نقدی"
                        },
                        new
                        {
                            Id = 51,
                            AccountTypeId = 5,
                            LanguageId = 3,
                            Translation = "Kasa"
                        },
                        new
                        {
                            Id = 52,
                            AccountTypeId = 5,
                            LanguageId = 4,
                            Translation = "Caisse"
                        },
                        new
                        {
                            Id = 53,
                            AccountTypeId = 5,
                            LanguageId = 5,
                            Translation = "Kasse"
                        },
                        new
                        {
                            Id = 54,
                            AccountTypeId = 5,
                            LanguageId = 6,
                            Translation = "نقدية"
                        },
                        new
                        {
                            Id = 55,
                            AccountTypeId = 5,
                            LanguageId = 7,
                            Translation = "Caja"
                        },
                        new
                        {
                            Id = 56,
                            AccountTypeId = 5,
                            LanguageId = 8,
                            Translation = "Cassa"
                        },
                        new
                        {
                            Id = 57,
                            AccountTypeId = 5,
                            LanguageId = 9,
                            Translation = "Касса"
                        },
                        new
                        {
                            Id = 58,
                            AccountTypeId = 5,
                            LanguageId = 10,
                            Translation = "现金"
                        },
                        new
                        {
                            Id = 59,
                            AccountTypeId = 5,
                            LanguageId = 11,
                            Translation = "現金"
                        },
                        new
                        {
                            Id = 60,
                            AccountTypeId = 5,
                            LanguageId = 12,
                            Translation = "Kassa"
                        },
                        new
                        {
                            Id = 61,
                            AccountTypeId = 6,
                            LanguageId = 1,
                            Translation = "Currency Exchange Clearing"
                        },
                        new
                        {
                            Id = 62,
                            AccountTypeId = 6,
                            LanguageId = 2,
                            Translation = "تسویه تبدیل ارز"
                        },
                        new
                        {
                            Id = 63,
                            AccountTypeId = 6,
                            LanguageId = 3,
                            Translation = "Döviz Değişim Takas"
                        },
                        new
                        {
                            Id = 64,
                            AccountTypeId = 6,
                            LanguageId = 4,
                            Translation = "Compte de compensation de change"
                        },
                        new
                        {
                            Id = 65,
                            AccountTypeId = 6,
                            LanguageId = 5,
                            Translation = "Währungsumrechnungs-Verrechnung"
                        },
                        new
                        {
                            Id = 66,
                            AccountTypeId = 6,
                            LanguageId = 6,
                            Translation = "تسوية صرف العملات"
                        },
                        new
                        {
                            Id = 67,
                            AccountTypeId = 6,
                            LanguageId = 7,
                            Translation = "Compensación de cambio de divisas"
                        },
                        new
                        {
                            Id = 68,
                            AccountTypeId = 6,
                            LanguageId = 8,
                            Translation = "Compensazione cambio valuta"
                        },
                        new
                        {
                            Id = 69,
                            AccountTypeId = 6,
                            LanguageId = 9,
                            Translation = "Расчетный счет обмена валют"
                        },
                        new
                        {
                            Id = 70,
                            AccountTypeId = 6,
                            LanguageId = 10,
                            Translation = "货币兑换结算"
                        },
                        new
                        {
                            Id = 71,
                            AccountTypeId = 6,
                            LanguageId = 11,
                            Translation = "為替交換精算"
                        },
                        new
                        {
                            Id = 72,
                            AccountTypeId = 6,
                            LanguageId = 12,
                            Translation = "Valutaväxlingsavräkning"
                        },
                        new
                        {
                            Id = 73,
                            AccountTypeId = 7,
                            LanguageId = 1,
                            Translation = "Opening Balance Equity"
                        },
                        new
                        {
                            Id = 74,
                            AccountTypeId = 7,
                            LanguageId = 2,
                            Translation = "حقوق صاحبان سهام افتتاحیه"
                        },
                        new
                        {
                            Id = 75,
                            AccountTypeId = 7,
                            LanguageId = 3,
                            Translation = "Açılış Bakiyesi Özsermayesi"
                        },
                        new
                        {
                            Id = 76,
                            AccountTypeId = 7,
                            LanguageId = 4,
                            Translation = "Capitaux propres du solde d'ouverture"
                        },
                        new
                        {
                            Id = 77,
                            AccountTypeId = 7,
                            LanguageId = 5,
                            Translation = "Eigenkapital der Eröffnungsbilanz"
                        },
                        new
                        {
                            Id = 78,
                            AccountTypeId = 7,
                            LanguageId = 6,
                            Translation = "حقوق الملكية للرصيد الافتتاحي"
                        },
                        new
                        {
                            Id = 79,
                            AccountTypeId = 7,
                            LanguageId = 7,
                            Translation = "Patrimonio del saldo inicial"
                        },
                        new
                        {
                            Id = 80,
                            AccountTypeId = 7,
                            LanguageId = 8,
                            Translation = "Patrimonio netto del saldo iniziale"
                        },
                        new
                        {
                            Id = 81,
                            AccountTypeId = 7,
                            LanguageId = 9,
                            Translation = "Капитал начального остатка"
                        },
                        new
                        {
                            Id = 82,
                            AccountTypeId = 7,
                            LanguageId = 10,
                            Translation = "期初余额权益"
                        },
                        new
                        {
                            Id = 83,
                            AccountTypeId = 7,
                            LanguageId = 11,
                            Translation = "開始残高資本"
                        },
                        new
                        {
                            Id = 84,
                            AccountTypeId = 7,
                            LanguageId = 12,
                            Translation = "Eget kapital för ingående balans"
                        });
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TenantId", "DocumentDate");

                    b.HasIndex("TenantId", "DocumentType");

                    b.ToTable("AccountingDocuments");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountingDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDocumentId");

                    b.HasIndex("LedgerAccountId");

                    b.HasIndex("TenantId", "LedgerAccountId", "IsDeleted");

                    b.ToTable("AccountingEntries");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.ApiAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("ApiAuditLogs");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountingDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrencyExchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MonetaryAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDocumentId");

                    b.HasIndex("CurrencyExchangeId");

                    b.HasIndex("MonetaryAccountId");

                    b.HasIndex("PersonId");

                    b.ToTable("Attachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachment_ExactlyOneOwner", "(CASE WHEN [AccountingDocumentId] IS NOT NULL THEN 1 ELSE 0 END +  CASE WHEN [PersonId] IS NOT NULL THEN 1 ELSE 0 END +  CASE WHEN [MonetaryAccountId] IS NOT NULL THEN 1 ELSE 0 END +  CASE WHEN [CurrencyExchangeId] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("tinyint");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "US Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EUR",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 3,
                            Code = "IRR",
                            DecimalPlaces = (byte)0,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Iranian Rial",
                            Symbol = "﷼"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TRY",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Turkish Lira",
                            Symbol = "₺"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AED",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "UAE Dirham",
                            Symbol = "د.إ"
                        },
                        new
                        {
                            Id = 6,
                            Code = "GBP",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "British Pound",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CAD",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Canadian Dollar",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AUD",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Australian Dollar",
                            Symbol = "A$"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CHF",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 10,
                            Code = "JPY",
                            DecimalPlaces = (byte)0,
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CNY",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "Chinese Yuan",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 12,
                            Code = "SEK",
                            DecimalPlaces = (byte)2,
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "Swedish Krona",
                            Symbol = "kr"
                        });
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.CurrencyExchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("FromDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromDocumentId");

                    b.HasIndex("ToDocumentId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.ToTable("CurrencyExchanges");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.DocumentTypeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("DocumentType", "LanguageId")
                        .IsUnique();

                    b.ToTable("DocumentTypeTranslations");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRightToLeft")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "fa",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsRightToLeft = true,
                            Name = "فارسی"
                        },
                        new
                        {
                            Id = 3,
                            Code = "tr",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 4,
                            Code = "fr",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "Français"
                        },
                        new
                        {
                            Id = 5,
                            Code = "de",
                            DisplayOrder = 5,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "Deutsch"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ar",
                            DisplayOrder = 6,
                            IsActive = true,
                            IsRightToLeft = true,
                            Name = "العربية"
                        },
                        new
                        {
                            Id = 7,
                            Code = "es",
                            DisplayOrder = 7,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "Español"
                        },
                        new
                        {
                            Id = 8,
                            Code = "it",
                            DisplayOrder = 8,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "Italiano"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ru",
                            DisplayOrder = 9,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "Русский"
                        },
                        new
                        {
                            Id = 10,
                            Code = "zh",
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "中文"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ja",
                            DisplayOrder = 11,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "日本語"
                        },
                        new
                        {
                            Id = 12,
                            Code = "sv",
                            DisplayOrder = 12,
                            IsActive = true,
                            IsRightToLeft = false,
                            Name = "Svenska"
                        });
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("HasBeenUsedInEntries")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPostingAccount")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId", "ParentId");

                    b.HasIndex("TenantId", "ParentId", "DisplayOrder")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("LedgerAccounts");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.MonetaryAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OpeningAccountingDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique();

                    b.HasIndex("OpeningAccountingDocumentId");

                    b.HasIndex("TenantId", "DisplayOrder")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("OpeningAccountingDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date");

                    b.Property<int>("PersonType")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TelNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique();

                    b.HasIndex("OpeningAccountingDocumentId");

                    b.HasIndex("TenantId", "DisplayOrder")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.SystemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TemplateKey", "LanguageId")
                        .IsUnique();

                    b.ToTable("SystemTemplates");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultCurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("DefaultLanguageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCurrencyId");

                    b.HasIndex("DefaultLanguageId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.BankAccount", b =>
                {
                    b.HasBaseType("PersonalFinanceApp.Domain.Entities.MonetaryAccount");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BankAccountType")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.CashAccount", b =>
                {
                    b.HasBaseType("PersonalFinanceApp.Domain.Entities.MonetaryAccount");

                    b.Property<bool>("IsPhysical")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable("CashAccounts", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PersonalFinanceApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountTypeTranslation", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountingDocument", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountingEntry", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountingDocument", "Document")
                        .WithMany("Entries")
                        .HasForeignKey("AccountingDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("LedgerAccount");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountingDocument", "AccountingDocument")
                        .WithMany()
                        .HasForeignKey("AccountingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PersonalFinanceApp.Domain.Entities.CurrencyExchange", "CurrencyExchange")
                        .WithMany()
                        .HasForeignKey("CurrencyExchangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PersonalFinanceApp.Domain.Entities.MonetaryAccount", "MonetaryAccount")
                        .WithMany()
                        .HasForeignKey("MonetaryAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PersonalFinanceApp.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountingDocument");

                    b.Navigation("CurrencyExchange");

                    b.Navigation("MonetaryAccount");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.CurrencyExchange", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountingDocument", "FromDocument")
                        .WithMany()
                        .HasForeignKey("FromDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountingDocument", "ToDocument")
                        .WithMany()
                        .HasForeignKey("ToDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromDocument");

                    b.Navigation("ToDocument");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.DocumentTypeTranslation", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.LedgerAccount", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("PersonalFinanceApp.Domain.Entities.LedgerAccount", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountType");

                    b.Navigation("Currency");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.MonetaryAccount", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountingDocument", "OpeningAccountingDocument")
                        .WithMany()
                        .HasForeignKey("OpeningAccountingDocumentId");

                    b.Navigation("Currency");

                    b.Navigation("LedgerAccount");

                    b.Navigation("OpeningAccountingDocument");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Person", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.AccountingDocument", "OpeningAccountingDocument")
                        .WithMany()
                        .HasForeignKey("OpeningAccountingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");

                    b.Navigation("LedgerAccount");

                    b.Navigation("OpeningAccountingDocument");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.SystemTemplate", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("PersonalFinanceApp.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("DefaultCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceApp.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("DefaultLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.AccountingDocument", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("PersonalFinanceApp.Domain.Entities.LedgerAccount", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
